Upgrade memcached helm chart
cortexproject/cortex-helm-chart pull request #142
Opened 2021-04-13 19:55 UTC by ryanprobus

* Upgrades memcached helm chart from 5.5.1 to 5.9.0 which adds support
  for specifying service account association and creation

Signed-off-by: Ryan Probus <ryan.probus@appian.com>

2021-06-06 11:52 UTC, ShuzZzle requested changes

2021-06-06 11:52 UTC, ShuzZzle commented on Chart.lock
> +  version: 5.10.1
Sorry for the wait time. Do you want to bump that up to 5.12.2? (the newest version)

However bitnami/memcached seems to have some quite severe [CVE's](https://artifacthub.io/packages/helm/bitnami/memcached?modal=security-report) ( i am guessing the old version does too...)

2021-06-06 11:52 UTC, ShuzZzle commented on Chart.yaml
> +version: 0.5.0
Please don't bump the Chart version on your own

2021-06-06 11:52 UTC, ShuzZzle commented on Chart.yaml
> +    version: 5.10.1
See first comment....duh :D

2021-06-06 11:54 UTC, ShuzZzle commented
@ryanprobus  Also please document your Change in the CHANGELOG.md

>  CHANGELOG.md updated - the order of entries should be [CHANGE], [FEATURE], [ENHANCEMENT], [BUGFIX]

2021-06-22 19:57 UTC, cabrinha commented
If there is a better memcached chart we can go with, let's take a look at it.

2021-06-22 21:01 UTC, ShuzZzle commented
> If there is a better memcached chart we can go with, let's take a look at it.

I wish...I think we just have to suck it up until maybe something like redis is supported or whatever

2021-06-22 21:09 UTC, ryanprobus commented
@ShuzZzle Sorry, was on vacation past couple weeks. Removed chart version bump, added to changelog and changed memcached upgrade from 5.5.1 to 5.13.0 (currently the newest published version).

2021-06-22 21:13 UTC, ryanprobus commented on Chart.lock
> +  version: 5.10.1
Upgraded to 5.13.0 (currently highest published version) since it had been a couple weeks since this comment.

2021-06-22 21:13 UTC, ryanprobus commented on Chart.yaml
> +version: 0.5.0
Removed.

2021-06-22 21:14 UTC, ryanprobus commented on Chart.yaml
> +    version: 5.10.1
See first comment's response =)

2021-06-23 08:34 UTC, ShuzZzle approved these changes

2021-06-23 08:35 UTC, merged