Added Missing ServiceMonitors "additionalLabels" in Values File
cortexproject/cortex-helm-chart pull request #146
Opened 2021-05-02 21:33 UTC by Xtigyro

2021-06-04 20:47 UTC, ShuzZzle requested changes

2021-06-04 20:47 UTC, ShuzZzle commented on CHANGELOG.md
> +* [BUGFIX] Added missing ServiceMonitors `additionalLabels` placeholders in `values.yaml`.
Please add your bugfix under the master / unreleased section. Not here!

2021-06-04 20:47 UTC, ShuzZzle commented on Chart.yaml
> +version: 0.4.2
I appreciate you helping us out, but the maintainers/owner will decide when to cut releases. So please remove that change

2021-06-06 11:21 UTC, Xtigyro commented on CHANGELOG.md
> +* [BUGFIX] Added missing ServiceMonitors `additionalLabels` placeholders in `values.yaml`.
@ShuzZzle Done.

2021-06-06 11:21 UTC, Xtigyro commented on Chart.yaml
> +version: 0.4.2
@ShuzZzle Done.

2021-06-06 11:29 UTC, ShuzZzle commented on Chart.yaml
> +version: 0.4.2
Dope I saw in the diff that one 0.3.0 enhancement had no PR number so I quickly added that :)

2021-06-06 11:29 UTC, ShuzZzle approved these changes
LGTM

2021-06-06 11:32 UTC, merged