fix pdb manifests
cortexproject/cortex-helm-chart pull request #157
Opened 2021-06-04 17:41 UTC by AndreZiviani

**What this PR does**:
Fixes the PodDisruptionBudget logic.

The manifest was probably created based on `target: all` mode, this PR creates a template for each component.

**Which issue(s) this PR fixes**:
Fixes #151 

**Checklist**
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2021-06-05 20:14 UTC, ShuzZzle requested changes

2021-06-05 20:14 UTC, ShuzZzle commented on CHANGELOG.md
> +* [BUGFIX] Fix PodDisruptionBudget templates. #156
I dont really know if that falls into the category BUGFIX but the PR number is definitely wrong. Should be #157

2021-06-07 12:25 UTC, AndreZiviani commented on CHANGELOG.md
> +* [BUGFIX] Fix PodDisruptionBudget templates. #156
Yeah, I wasn't sure what to use, maybe enchancement?

> the PR number is definitely wrong. Should be #157
:facepalm:

2021-06-07 13:54 UTC, ShuzZzle commented
Thank you so much!
However #144 (don't really know why) just did the same thing you did. And we are currently in the process of merging this PR. So even though everything is correct here, I might have to close it in favor of #144

:disappointed:

2021-06-07 13:59 UTC, AndreZiviani commented
Looks like that implementation has some improvements over mine, I don't mind using that instead. Thanks for the review!

2021-06-07 13:59 UTC, closed without merging