Enable / Disable Security Context
cortexproject/cortex-helm-chart pull request #158
Opened 2021-06-06 15:45 UTC by 1995parham

This PR makes the security context removable from Kubernetes YAML files, it means you can really disable them in case of not wanting them. closes #140

2021-06-06 16:57 UTC, ShuzZzle commented
@1995parham Somebody didn't use the PR template :D

Please fill out the changelog:
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2021-06-06 16:58 UTC, ShuzZzle requested changes

2021-06-06 16:58 UTC, ShuzZzle commented on templates/alertmanager-dep.yaml
> +
can you remove the blank line, please?

2021-06-06 17:16 UTC, 1995parham commented
Thanks for your comments. I have fixed them.

2021-06-06 21:06 UTC, ShuzZzle requested changes
Also your forgot to DCO your commit

2021-06-06 21:06 UTC, ShuzZzle commented on CHANGELOG.md
> +- [ENHANCEMENT] Add Enable/Disable for security context #140
Buddy ....

 > the order of entries should be [CHANGE], [FEATURE], [ENHANCEMENT], [BUGFIX]
 
 Also did you really reformat the entire CHANGELOG.md? :laughing:

2021-06-06 21:19 UTC, 1995parham commented on CHANGELOG.md
> +- [ENHANCEMENT] Add Enable/Disable for security context #140
Sorry, it was the prettifier and I have totally forgotten it. I will fix it now.

2021-06-06 21:22 UTC, 1995parham commented on CHANGELOG.md
> +- [ENHANCEMENT] Add Enable/Disable for security context #140
About the reformat, revert it or it is okey?

2021-06-06 21:23 UTC, ShuzZzle commented on CHANGELOG.md
> +- [ENHANCEMENT] Add Enable/Disable for security context #140
the order matters but you don't have to fix the prettifier

2021-06-06 21:24 UTC, 1995parham commented on CHANGELOG.md
> +- [ENHANCEMENT] Add Enable/Disable for security context #140
Thanks 👍

2021-06-06 21:33 UTC, ShuzZzle commented on templates/alertmanager-dep.yaml
> +      securityContext: {{- omit .Values.alertmanager.securityContext "enabled" | toYaml | nindent 8 }}
I just realised something, when you disable the securityContext for the **POD** then the securityContext is still active for the **container** as you can see in L86-88

2021-06-06 21:33 UTC, ShuzZzle commented on templates/alertmanager-dep.yaml
> +      securityContext: {{- omit .Values.alertmanager.securityContext "enabled" | toYaml | nindent 8 }}
Is that what we want?

2021-06-06 21:38 UTC, 1995parham commented on templates/alertmanager-dep.yaml
> +      securityContext: {{- omit .Values.alertmanager.securityContext "enabled" | toYaml | nindent 8 }}
These are two different things I think and we can configure them separately. as you can see here we can have two different variables for them:

https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/statefulset.yaml

if you agree I can do this two but it introduces new variable.

2021-06-06 21:43 UTC, ShuzZzle commented on templates/alertmanager-dep.yaml
> +      securityContext: {{- omit .Values.alertmanager.securityContext "enabled" | toYaml | nindent 8 }}
Yeah that might be a good idea. Maybe refactor
```YAML
          securityContext:
            readOnlyRootFilesystem: true
```

into values.yml and do the same as above only with the containerSecurityContext variable. So I guess something amongst these lines

```YAML
[...]
      securityContext: {{- omit .Values.ruler.containerSecurityContext "enabled" | toYaml | nindent 8 }}
```
I think thats cool since we only have 1 container per "Pod" anyway. Otherwise that might a problem if you want to configure containers seperately

2021-06-06 21:45 UTC, ShuzZzle commented on templates/alertmanager-dep.yaml
> +      securityContext: {{- omit .Values.alertmanager.securityContext "enabled" | toYaml | nindent 8 }}
Or (probably the better idea) we could just call containerSecurityContext what is actually IS, i.e. rulerSecurityContext alertmanagersecurityContext ....

2021-06-06 21:46 UTC, ShuzZzle commented on templates/alertmanager-dep.yaml
> +      securityContext: {{- omit .Values.alertmanager.securityContext "enabled" | toYaml | nindent 8 }}
@cabrinha Whats your take on this

2021-06-07 20:52 UTC, ShuzZzle commented
Hi @1995parham 

We just merged #144. Due to the massive refactor you will have to rebase master and make sure that you don't actually add back the old files, since the location changed to a more easily maintainable folder structure

2021-06-07 21:43 UTC, 1995parham commented
Yes, I will rebase it. about the permissions, they had execution permission and I removed it.

2021-06-12 21:40 UTC, ShuzZzle commented on templates/alertmanager-dep.yaml
> +      securityContext: {{- omit .Values.alertmanager.securityContext "enabled" | toYaml | nindent 8 }}
@1995parham Whats your opinion? Soon we will have more than 1 container in the deployment/set. When this happens it's not super clear anymore what containerSecurityContext actually does. Should we rename that to rulerSecurityContext so we can differentiate between multiple containers within in a deployment?

2021-06-13 08:52 UTC, 1995parham commented on templates/alertmanager-dep.yaml
> +      securityContext: {{- omit .Values.alertmanager.securityContext "enabled" | toYaml | nindent 8 }}
I think we can prefix them with container names but also there is no harm if we use the same security context on all of them.
as an example, Bitnami charts do the same [here](https://github.com/bitnami/charts/blob/master/bitnami/kong/templates/dep-ds.yaml).

2021-06-13 10:03 UTC, ShuzZzle approved these changes
Reverted the CHANGELOG.md back to the original format. I think thats better but yeah LGTM!

2021-06-13 10:19 UTC, ShuzZzle approved these changes

2021-06-13 11:26 UTC, 1995parham commented
Thanks for your changes and sorry about the Nginx security context.

2021-06-13 11:37 UTC, merged