feat: store-gateway nginx path
cortexproject/cortex-helm-chart pull request #167
Opened 2021-06-23 04:13 UTC by cabrinha

**What this PR does**:

Exposes a path via NGINX to reach store-gateway service.

**Checklist**
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2021-06-23 08:13 UTC, ShuzZzle requested changes

2021-06-23 08:13 UTC, ShuzZzle commented on templates/nginx-config.yaml
> +          proxy_pass      http://{{ template "cortex.fullname" . }}-store-gateway.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.config.server.http_listen_port }}$request_uri;
That Service doesn't exist. Should be -headless (See: #166 ). By the way we should really have a normal ClusterIP service for this

2021-06-23 12:14 UTC, ShuzZzle commented on templates/nginx-config.yaml
> +          proxy_pass      http://{{ template "cortex.fullname" . }}-store-gateway.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.config.server.http_listen_port }}$request_uri;
When #169 is implemented this actually exists then

2021-06-24 06:45 UTC, ShuzZzle commented on templates/nginx-config.yaml
> +          proxy_pass      http://{{ template "cortex.fullname" . }}-store-gateway.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.config.server.http_listen_port }}$request_uri;
Merged in #169 therefore resolved.

2021-06-24 06:48 UTC, ShuzZzle commented on CHANGELOG.md
> +* [ENHANCEMENT] Allow store-gateways to be reached via the NGINX ingress, allowing access to the ring, etc.
Holy Smokes :D thats an super old version of the chart, no? Please rebase

2021-06-24 06:49 UTC, ShuzZzle commented on CHANGELOG.md
> +* [ENHANCEMENT] Allow store-gateways to be reached via the NGINX ingress, allowing access to the ring, etc.
Also the order is incorrect and the PR number is missing to the changelog entry

2021-06-24 17:42 UTC, cabrinha commented
I'll reopen this PR

2021-06-24 17:42 UTC, closed without merging