add autoscaler for queriers
cortexproject/cortex-helm-chart pull request #190
Opened 2021-07-30 21:29 UTC by kd7lxl

**What this PR does**:
Adds a `HorizontalPodAutoscaler` for the queriers.

https://cortexmetrics.io/docs/architecture/#querier
> Queriers are stateless and can be scaled up and down as needed.

**Checklist**
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2021-07-31 10:53 UTC, ShuzZzle requested changes

2021-07-31 10:53 UTC, ShuzZzle commented on values.yaml
> +    targetMemoryUtilizationPercentage: 0  # 80
nice but i don't like the defaults. querier is also a highly dependant memory process, even though query frontend already splits querier by day.

I actually don't think CPU matters that much

2021-08-02 17:23 UTC, ShuzZzle approved these changes

2021-08-02 17:24 UTC, ShuzZzle commented on values.yaml
> +    targetMemoryUtilizationPercentage: 0  # 80
@cabrinha what's your opinion?

2021-08-02 17:31 UTC, kd7lxl commented on values.yaml
> +    targetMemoryUtilizationPercentage: 0  # 80
Somewhat related, I've spent a lot of time tuning resource definitions for each Cortex component and still don't feel like I've got it dialed in. I'd appreciate any real world knowledge people could share in the wiki or elsewhere.

2021-08-02 21:22 UTC, ShuzZzle commented on values.yaml
> +    targetMemoryUtilizationPercentage: 0  # 80
>  still don't feel like I've got it dialed in

Yep its like a never ending story :)

2021-08-02 22:01 UTC, cabrinha commented
It'd also be nice if we could add HPA for every component that can safely be autoscaled.

2021-08-02 22:09 UTC, kd7lxl commented
> It'd also be nice if we could add HPA for every component that can safely be autoscaled.

I've been adding them one at a time as a learn/recognize that they are safe to autoscale, and by what metric. If someone with more operational experience could share appropriate scaling metrics for each component, I could add the autoscalers.

2021-08-03 05:50 UTC, merged