Add basic auth configuration options to Nginx
cortexproject/cortex-helm-chart pull request #206
Opened 2021-08-30 04:13 UTC by logston

**What this PR does**:
  This commit adds the ability to include an `auth_basic` and
  `auth_basic_user_file` directive in the Nginx configuration file.

**Which issue(s) this PR fixes**:
Fixes #205 

**Checklist**
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2021-08-30 10:16 UTC, ShuzZzle commented
Hi @logston,

Thank you for contribution. You will also have to update the README.md with your updated values.yml entry. See the lint-test Job for more details :)

2021-08-30 19:11 UTC, ShuzZzle requested changes
Please update the Readme.md with your new values.yml config option

2021-08-31 04:41 UTC, logston commented
Thanks @ShuzZzle! I've updated the PR.

2021-08-31 05:57 UTC, ShuzZzle requested changes

2021-08-31 05:57 UTC, ShuzZzle commented on README.md
> +| nginx.&ZeroWidthSpace;config.&ZeroWidthSpace;basicAuthMountPath | string | `""` | Path of `auth_basic_user_file` |
```suggestion
| nginx.&ZeroWidthSpace;config.&ZeroWidthSpace;basicAuthMountPath | string | `""` | (optional) Mount path of basic auth secret. In order to use this path, a secret with htpasswd contexts should be mounted to the container. For example:  extraVolumes:  - name: nginx-htpasswd    secret:      defaultMode: 420      secretName: nginx-htpasswd  extraVolumeMounts:  - mountPath: /keys/    name: nginx-htpasswd |
```

2021-08-31 05:57 UTC, ShuzZzle commented on README.md
> +| nginx.&ZeroWidthSpace;config.&ZeroWidthSpace;basicAuthMountPath | string | `""` | Path of `auth_basic_user_file` |
should be like this (must match the generated spec from values.yaml, using helm-docs)

2021-08-31 13:43 UTC, Eraac commented
Please also disable basic_auth for /healthz path (for kubernetes health check)

2021-08-31 17:52 UTC, ShuzZzle commented on templates/nginx/nginx-config.yaml
>          }
```suggestion
        location = /healthz {
          auth_basic "off";
          return 200 'alive';
        }
```
Needs to be tested, but I think that should disable basic_auth for healthz checkpoint

2021-08-31 17:52 UTC, ShuzZzle commented on templates/nginx/nginx-config.yaml
>          }
@Eraac Something like this?

2021-08-31 19:54 UTC, Eraac commented on templates/nginx/nginx-config.yaml
>          }
@ShuzZzle I'm not 100% sure about the quote but otherwise is the only place where it is needed

2021-08-31 23:36 UTC, logston commented on README.md
> +| nginx.&ZeroWidthSpace;config.&ZeroWidthSpace;basicAuthMountPath | string | `""` | Path of `auth_basic_user_file` |
Oh! Many thanks.

2021-08-31 23:56 UTC, logston commented on templates/nginx/nginx-config.yaml
>          }
I don't think this will have a difference given Nginx's use of [access phases](http://nginx.org/en/docs/dev/development_guide.html#http_phases). 

See this SO post: https://stackoverflow.com/questions/67975464/why-doesnt-basic-auth-work-with-a-simple-nginx-return-statement

However, I can add comment for clarity on why nginx will still return 200 in the event basic auth is enabled.

2021-09-01 11:00 UTC, ShuzZzle commented on templates/nginx/nginx-config.yaml
> +          # evaluated.
I assume you tested this on your local setup? If yes, then its fine with me. Unfortunately the CI doesn't test this change

2021-09-01 11:01 UTC, ShuzZzle approved these changes

2021-09-01 15:02 UTC, kd7lxl commented on values.yaml
> +    basicAuthMountPath: ""
The usage here is a little awkward. If this is going to be a feature of the chart, it could do the mount work for you too. This parameter would change to something like `basicAuthSecretName: ""` and the template would get a new conditional statement in the volume mounts section.

2021-09-01 16:35 UTC, kd7lxl commented on templates/nginx/nginx-config.yaml
> +        auth_basic_user_file {{ .Values.nginx.config.basicAuthMountPath }};
Help me understand the use case for this -- it seems pretty narrow.  It looks like this will require basic auth, but not actually use the username.

To protect the `/api/v1/push` endpoint from privilege escalation / users masquerading as other users, I would expect nginx to set the `X-Scope-OrgId` header to the basic username it received, or something like that.

Since this doesn't do that, it looks like it's only useful for creating admin users, who are expected to be trusted with all endpoints and orgs. Is that right? Is that the only use case for this?

2021-09-02 05:13 UTC, logston commented on templates/nginx/nginx-config.yaml
> +          # evaluated.
I have. I tested it in a staging env in GCP.

2021-09-02 05:14 UTC, logston commented on values.yaml
> +    basicAuthMountPath: ""
Sure thing. I can add that.

2021-09-02 05:22 UTC, logston commented on templates/nginx/nginx-config.yaml
> +        auth_basic_user_file {{ .Values.nginx.config.basicAuthMountPath }};
The basic auth file contains both the user name and the password in a hashed format. A series of them to be precise. Please see this link for an example: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

As I understanding it, `X-Scope-OrgId` is used for tenant identification, not authentication/authorization. See here: 
https://cortexmetrics.io/docs/guides/auth/

> All Cortex components take the tenant ID from a header X-Scope-OrgID on each request. A tenant (also called “user” or “org”) is the owner of a set of series written to and queried from Cortex. All Cortex components **trust this value completely: if you need to protect your Cortex installation from accidental or malicious calls then you must add an additional layer of protection.**

My particular use case requires that Prometheus installations write over the public internet to a Cortex installation. In order to provide some security (beyond TLS), I need one of the solutions that Promtheus supports in its `remote_write` configuration. The simplest is basic auth. Please see this link for a complete list: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write

2021-09-02 15:21 UTC, kd7lxl commented on templates/nginx/nginx-config.yaml
> +        auth_basic_user_file {{ .Values.nginx.config.basicAuthMountPath }};
> As I understanding it, `X-Scope-OrgId` is used for tenant identification, not authentication/authorization.

Authentication is the process of verifying the identity of a user or process. This is why I was asking how http basic auth might tie to tenant identification.

Here (my employer), we use http basic auth to authenticate a Prometheus instance _and_ map it to the corresponding tenant with `X-Scope-OrgId`. In this way, we are doing both the authentication and authorization with http basic auth. There's no way for our http basic auth users to access each other's data.

With this change, I just want to make sure the use case is clearly documented, so that users understand that it does not relate to [Cortex auth](https://cortexmetrics.io/docs/guides/auth/) and allows http basic auth users to access each other's data. All users must be completely trusted.

2021-09-02 15:40 UTC, kd7lxl commented on templates/nginx/nginx-config.yaml
> +        auth_basic_user_file {{ .Values.nginx.config.basicAuthMountPath }};
Maybe the way this detail could be documented is by giving an example of how one might add Cortex auth to the config, something like this:
> When using http basic auth and Cortex multi-tenancy, the username can be used as the tenant id:
> ```yaml
> setHeaders:
>   X-Scope-OrgId: $remote_user
> ```
Not sure if this will work with the current ordering of the nginx config (`setHeaders` is before auth)

2021-09-02 17:14 UTC, logston commented on templates/nginx/nginx-config.yaml
> +        auth_basic_user_file {{ .Values.nginx.config.basicAuthMountPath }};
>  I just want to make sure the use case is clearly documented, so that users understand that it does not relate to Cortex auth

Got it. I can add that in.

2021-09-02 17:49 UTC, logston commented
Hey @kd7lxl, if the docs updates are sufficient, can I get a 👍 to merge?

2021-09-02 18:48 UTC, kd7lxl commented on values.yaml
> +    # along with a basic auth header.
This is worded backwards... _passing_ the header requires trusting the client. Setting the header in the nginx config with appropriately scope the tenants.
```suggestion
    # prevent one tenant from viewing the metrics of another. To ensure tenants
    # are scoped appropriately, explicitly set the `X-Scope-OrgID` header
    # in the nginx config. Example
    #   setHeaders:
    #     X-Scope-Org-Id: $remote_user
```

2021-09-03 04:15 UTC, logston commented on values.yaml
> +    # along with a basic auth header.
Ok. Updated.

2021-09-03 16:05 UTC, kd7lxl approved these changes

2021-09-03 16:53 UTC, ShuzZzle approved these changes

2021-09-03 17:41 UTC, logston commented
Thanks for the reviews! Unfortunately, I don't access to merge this PR:

> Only those with write access to this repository can merge pull requests.

Can either one of you merge this?

2021-09-03 17:47 UTC, merged

2021-09-03 18:51 UTC, logston commented
Thanks @ShuzZzle! Lastly, I see that releases are cut every 1 - 3 months or so. Is there any projected date for the next release? Many thanks.

2021-09-03 18:53 UTC, ShuzZzle commented
> Thanks @ShuzZzle! Lastly, I see that releases are cut every 1 - 3 months or so. Is there any projected date for the next release? Many thanks.

Uhm unfortunately there is no such release plan as of now. Soon™