Support customizing the nginx config with values
cortexproject/cortex-helm-chart pull request #213
Opened 2021-09-01 15:55 UTC by kd7lxl

**What this PR does**:
There are a lot of use cases for nginx and not all of them are supported by the chart. This change allows adding custom configuration to nginx, so that users can implement what they need with nginx without a change to the chart.

**Checklist**
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2021-09-04 12:59 UTC, ShuzZzle requested changes
Did the CHANGELOG entry get lost while rebasing?

2021-09-04 14:38 UTC, ShuzZzle approved these changes

2021-09-04 14:39 UTC, ShuzZzle commented
yeah "let CI build the README" uhm it only triggers on changes to values.yml :(

2021-09-04 16:04 UTC, kd7lxl commented
> yeah "let CI build the README" uhm it only triggers on changes to values.yml :(

Hmm, as a PR check, we really want it to run on the full diff of the PR.

2021-09-04 19:11 UTC, ShuzZzle approved these changes

2021-09-04 19:18 UTC, ShuzZzle commented
@kd7lxl Ah great, did we just bugged it? Seems to be stuck...maybe due to the skip ci tag.

2021-09-10 17:46 UTC, kd7lxl commented
> @kd7lxl Ah great, did we just bugged it? Seems to be stuck...maybe due to the skip ci tag.

Fixed in #217

2021-09-10 17:51 UTC, merged