- Fixed hardcoding of containerSecurityContext in Ingester statefulset
cortexproject/cortex-helm-chart pull request #258
Opened 2021-11-17 10:28 UTC by RyanW8

- Brought setting of containerSecurityContext for the Ingester statefulset inline with other components configuration

**What this PR does**:

- Removes the hardcoded value for containerSecurityContext in the ingester statefulset
- Brough the configuration of the ingester containerSecurityContext inline with what is documented in the values.

**Which issue(s) this PR fixes**:

Didn't raise an issue

2021-11-17 12:12 UTC, ShuzZzle requested changes

2021-11-17 12:12 UTC, ShuzZzle commented on templates/ingester/ingester-statefulset.yaml
> -            readOnlyRootFilesystem: true
This should be
```yaml
          {{- if .Values.ingester.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.ingester.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
```

2021-11-17 15:57 UTC, kd7lxl commented on templates/ingester/ingester-statefulset.yaml
> -            readOnlyRootFilesystem: true
Thanks for catching this. We want to retain the default of `readOnlyRootFilesystem: true` for sure.

2021-11-18 09:00 UTC, ShuzZzle approved these changes

2021-11-19 16:11 UTC, kd7lxl approved these changes

2021-11-19 18:54 UTC, merged