Disable ingester liveness probes by default.
cortexproject/cortex-helm-chart pull request #263
Opened 2021-11-24 15:30 UTC by jmcarp

**What this PR does**:

Based on cortex docs at
https://cortexmetrics.io/docs/guides/running-cortex-on-kubernetes/#take-extra-care-with-ingesters,
liveness probes for ingesters are not recommended: "We do not recommend
configuring a liveness probe on ingesters - killing them is a last resort and
should not be left to a machine."

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2021-11-24 16:41 UTC, ShuzZzle requested changes

2021-11-24 16:41 UTC, ShuzZzle commented on templates/ingester/ingester-dep.yaml
> +          {{ -end }}
```suggestion
          {{- end }}
```
syntax error

2021-11-24 16:41 UTC, ShuzZzle commented on values.yaml
> +  #     port: http-metrics
Personally I don't like comments like these within the values.yml. I just think its confusing and clutters the file alot.

May I suggest something like this? (adopted for helm-docs. See: #227 )
```suggestion
  # -- Liveness probes for ingesters are not recommended.
  # Ref: https://cortexmetrics.io/docs/guides/running-cortex-on-kubernetes/#take-extra-care-with-ingesters
  livenessProbe:
```

2021-11-24 16:47 UTC, ShuzZzle commented on values.yaml
> +  #     port: http-metrics
might also work with
```yaml
livenessProbe: []
```

2021-11-24 18:42 UTC, kd7lxl commented on values.yaml
> +  #     port: http-metrics
It's an object so it should be `{}`.
```suggestion
  # -- Liveness probes for ingesters are not recommended.
  #  Ref: https://cortexmetrics.io/docs/guides/running-cortex-on-kubernetes/#take-extra-care-with-ingesters
  livenessProbe: {}
  #   httpGet:
  #     path: /ready
  #     port: http-metrics
```

2021-11-24 19:02 UTC, ShuzZzle commented on values.yaml
> +  #     port: http-metrics
right.. mea culpa

2021-11-24 19:13 UTC, ShuzZzle commented on CHANGELOG.md
> +* [BUGFIX] Disable ingester liveness probes by default. #263
How is that a BUGFIX, should be just a simple CHANGE

2021-11-24 19:29 UTC, ShuzZzle approved these changes
yep fine by me

2021-11-28 12:06 UTC, ShuzZzle commented on values.yaml
> +  #     port: http-metrics
```suggestion
```

I would still prefer if you remove these comments :), they don't do anything unless you actually check `values.yaml`

2021-11-29 22:46 UTC, kd7lxl approved these changes

2021-11-29 22:49 UTC, merged