Optionally set service account per dep/statefulset.
cortexproject/cortex-helm-chart pull request #264
Opened 2021-11-25 04:59 UTC by jmcarp

**What this PR does**:

Different cortex components might require different cloud provider
permissions. When using gke workload identity, pod iam permissions are
managed by kubernetes service account. This patch allows operators to
use different service accounts for each deployment or statefulset to
support fine-grained control of iam permissions in this scenario.

**Which issue(s) this PR fixes**:
Fixes #251

**Checklist**
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2021-11-28 11:55 UTC, ShuzZzle commented on values.yaml
> +    name:
```suggestion
    # -- "" disables the individual serviceAccount and uses the global serviceAccount for that component
    name: ""
```

Small suggestion, I would prefer that than having no value at all. Looks odd to me

2021-11-28 11:56 UTC, ShuzZzle commented
Oh and please rebase your PR's

2021-11-29 16:33 UTC, ShuzZzle approved these changes

2021-11-29 17:35 UTC, kd7lxl commented on templates/alertmanager/alertmanager-dep.yaml
> +      serviceAccountName: {{ with .Values.alertmanager.serviceAccount.name }}{{ . }}{{ else }}{{ template "cortex.serviceAccountName" . }}{{ end }}
Is there any specific benefit to using `with`/`else` here rather than [`| default`](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-default-function)?

2021-11-29 18:13 UTC, ShuzZzle commented on templates/alertmanager/alertmanager-dep.yaml
> +      serviceAccountName: {{ with .Values.alertmanager.serviceAccount.name }}{{ . }}{{ else }}{{ template "cortex.serviceAccountName" . }}{{ end }}
ah nice idea! but it should be
```yaml
{{ .Values.alertmanager.serviceAccount.name | default (include "cortex.serviceAccountName" .) }}
```
right?

2021-11-29 23:30 UTC, ShuzZzle requested changes
should be include in order for it to work

2021-11-29 23:30 UTC, ShuzZzle commented on templates/alertmanager/alertmanager-dep.yaml
> +      serviceAccountName: {{ .Values.alertmanager.serviceAccount.name | default (template "cortex.serviceAccountName" . ) }}
```suggestion
      serviceAccountName: {{ .Values.alertmanager.serviceAccount.name | default (include "cortex.serviceAccountName" . ) }}
```

2021-11-30 00:36 UTC, jmcarp commented on templates/alertmanager/alertmanager-dep.yaml
> +      serviceAccountName: {{ with .Values.alertmanager.serviceAccount.name }}{{ . }}{{ else }}{{ template "cortex.serviceAccountName" . }}{{ end }}
Thanks, applied this throughout.

2021-11-30 00:42 UTC, kd7lxl approved these changes

2021-11-30 08:47 UTC, ShuzZzle approved these changes

2021-11-30 08:50 UTC, merged