Feat/query scheduler
cortexproject/cortex-helm-chart pull request #268
Opened 2021-11-26 22:12 UTC by marquezika

**What this PR does**:

This MR adds the component Query-Scheduler - this makes scaling query frontend easier.

_Reference: [scaling-query-frontend](https://cortexmetrics.io/docs/operations/scaling-query-frontend/#query-scheduler)._

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2021-11-28 12:03 UTC, ShuzZzle requested changes
Hi,

Thank you for your contribution. Could you please do the following?

- [ ] Rebase against current master
- [ ] implement suggestions
- [ ] add ci test for query-scheduler to `test-deployment-values.yaml` or both

2021-11-29 12:28 UTC, ShuzZzle commented on templates/query-scheduler/query-scheduler-servicemonitor.yaml
> +{{ toYaml .Values.query_scheduler.serviceMonitor.additionalLabels | indent 4 }}
i know the other service monitors are exactly like this but I think we should move everything to nindent. All of the other stuff already is

2021-11-29 12:28 UTC, ShuzZzle commented on templates/query-scheduler/query-scheduler-servicemonitor.yaml
> +{{ toYaml .Values.query_scheduler.serviceMonitor.annotations | indent 4 }}
```suggestion
    {{- toYaml .Values.query_scheduler.serviceMonitor.annotations | nindent 4 }}
```

2021-11-29 12:49 UTC, marquezika commented
Hi @ShuzZzle.

Sure, I gonna implement these changes - thanks for reviewing.

2021-12-04 22:46 UTC, ShuzZzle commented
@marquezika Need some help? :)

2022-03-03 08:23 UTC, nschad commented
Hey @marquezika,

Do you still wanna do this? I already rebased the branch on the current master otherwise I'm happy to finish this PR

2022-03-14 13:45 UTC, nschad approved these changes

2022-03-14 13:53 UTC, nschad requested changes
/

2022-03-14 14:10 UTC, nschad approved these changes
@kd7lxl I think this is okay like this

might need some tests tho

2022-03-14 14:44 UTC, kd7lxl reviewed
LGTM. Yes, please add some CI values to exercise it in the tests. Then we can merge.

2022-03-14 16:04 UTC, merged