Optionally pass cortex config as configmap.
cortexproject/cortex-helm-chart pull request #280
Opened 2021-12-01 22:52 UTC by jmcarp

**What this PR does**:
Optionally pass cortex config as configmap.

Note: I only updated the ingestor templates so far, to verify that the approach makes sense. If it does, I'll copy and paste the updated volume to the other templates.

**Which issue(s) this PR fixes**:
Fixes #235.

**Checklist**
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2021-12-03 14:04 UTC, ShuzZzle commented
Nice!

with that approach however, we should really have the s3 credentials (or similiar) **not** in the configMap

2021-12-04 22:40 UTC, ShuzZzle commented on values.yaml
> +useConfigMap: true
I wouldn't enable this per default personally

2021-12-04 22:45 UTC, ShuzZzle requested changes
Hey, thank you for your contribution.

Can you please add the CHANGELOG.md entry?
Also we would need to add a mechanism similiar to: [This](https://github.com/cortexproject/cortex-helm-chart/blob/master/templates/ingester/ingester-dep.yaml#L33) 

So we can restart components when configmap changes, right now we can't use something like configmap reloader AFAIK

2021-12-05 05:50 UTC, jmcarp commented
Updated, lmk if I missed anything.

2021-12-05 13:34 UTC, ShuzZzle reviewed
I will have another glance tomorrow but this looks really good. Thanks!

2021-12-05 13:34 UTC, ShuzZzle commented on CHANGELOG.md
> +* [FEATURE] Optionally manage cortex config as configmap. #280
technically FEATURE's should be the first entry in the changelog

2021-12-06 09:43 UTC, ShuzZzle approved these changes
I re-edited the guide, because inline code blocks completely broke the the text unfortunately. We will have to adjust the markdown processor something like that in the future

2021-12-06 13:21 UTC, ShuzZzle commented on templates/configmap.yaml
> +  name: {{ template "cortex.fullname" . }}
```suggestion
  name: {{ template "cortex.fullname" . }}-config
```
tiny improvement idea

2021-12-06 16:41 UTC, ShuzZzle commented
@jmcarp Please be careful when rebasing, my changes to the guide were lost

2021-12-06 16:48 UTC, kd7lxl approved these changes

2021-12-06 17:08 UTC, jmcarp commented
Ack, sorry, not used to collaborating on a branch 😓

2021-12-06 18:50 UTC, merged