Disable ingester startup probe by default.
cortexproject/cortex-helm-chart pull request #286
Opened 2021-12-10 00:27 UTC by jmcarp

Following up on #263, we should disable ingester startup probes by
default, since the cortex docs note that killing ingesters "should not
be left to a machine". I've also noticed restart loops due to the
startup probe when starting ingesters after downtime, when remote
writers have a backlogs of metrics to send.

**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

cc @logston

2021-12-10 09:46 UTC, ShuzZzle commented
> Error: Deployment.apps "cortex-krvb4b4cu4-ingester" is invalid: spec.template.spec.containers[0].startupProbe: Required value: must specify a handler type

```yaml
          startupProbe:
            {{- toYaml .Values.ingester.startupProbe | nindent 12 }}
            ```
you will have to wrap the startupProbe in a if clause

2021-12-10 09:48 UTC, ShuzZzle requested changes
> Error: Deployment.apps "cortex-krvb4b4cu4-ingester" is invalid: spec.template.spec.containers[0].startupProbe: Required value: must specify a handler type

```yaml
          startupProbe:
            {{- toYaml .Values.ingester.startupProbe | nindent 12 }}
```

you will have to wrap the startupProbe in an if clause or use `with`
Also please track your `CHANGE` in the CHANGELOD.md

2021-12-10 21:26 UTC, jmcarp commented
Updated!

2021-12-11 20:40 UTC, ShuzZzle requested changes

2021-12-11 20:40 UTC, ShuzZzle commented on CHANGELOG.md
> +* [CHANGE] Disable ingester startup probes by default. #286
- the order of entries should be [CHANGE], [FEATURE], [ENHANCEMENT], [BUGFIX]

2021-12-11 20:40 UTC, ShuzZzle commented on templates/ingester/ingester-statefulset.yaml
> +          {{- end}}
```suggestion
          {{- end }}
```

2021-12-11 20:40 UTC, ShuzZzle commented on templates/ingester/ingester-dep.yaml
> +          {{- end}}
```suggestion
          {{- end }}
```

why do you hate spaces 😆

2021-12-11 20:40 UTC, ShuzZzle commented on CHANGELOG.md
> +* [CHANGE] Disable ingester startup probes by default. #286
I'm gonna be that guy but I mean its right in the PR template

2021-12-11 23:33 UTC, jmcarp commented on templates/ingester/ingester-dep.yaml
> +          {{- end}}
Sorry, I think I must have been copying and pasting blocks with missing whitespace. I fixed this and other whitespace throughout.

2021-12-11 23:36 UTC, ShuzZzle commented on templates/ingester/ingester-statefulset.yaml
> +          {{- end}}
^^^ still here

2021-12-11 23:38 UTC, ShuzZzle approved these changes
there are like 2x `{{- end}}` left but the rest is LGTM!

2021-12-11 23:54 UTC, jmcarp commented
> there are like 2x {{- end}}

fml, sorry

2021-12-12 00:34 UTC, kd7lxl commented on README.md
> -| ingester.&ZeroWidthSpace;livenessProbe | object | `{}` | Liveness probes for ingesters are not recommended.  Ref: https://cortexmetrics.io/docs/guides/running-cortex-on-kubernetes/#take-extra-care-
It would be nice to preserve this doc on the livenessProbe field.

2021-12-12 19:55 UTC, kd7lxl approved these changes

2021-12-12 19:55 UTC, merged