Added /api/prom/rules and /api/prom/api/v1/alerts endpoints to Nginx …
cortexproject/cortex-helm-chart pull request #291
Opened 2021-12-14 10:58 UTC by RyanW8

**What this PR does**:

Adds the following HTTP endpoints to the Nginx configuration
- `/api/prom/rules` -> Cortex Ruler
- `/api/prom/api/v1/alerts` -> Cortex Alertmanager

This endpoints are used by Grafana 8 unified alerting.

**Which issue(s) this PR fixes**:
Fixes #257 

**Checklist**
- [ ] `CHANGELOG.md` updated

2021-12-15 08:43 UTC, ShuzZzle requested changes

2021-12-15 08:43 UTC, ShuzZzle commented on CHANGELOG.md
> +* [BUGFIX] Added api endpoints for Grafana 8 unified alerting
```suggestion
* [ENHANCEMENT] Added api endpoints for Grafana 8 unified alerting
```
We are adding functionality out-of-the box, not fixing anything

2021-12-16 12:33 UTC, ShuzZzle requested changes
To be honest I was kinda hoping for Ideas on how to improve/reorganize the location section in the nginx config rather than just adding 2 more endpoints. It would be cool if we could have an "simplified" config for the entire cortex http API

2021-12-16 12:33 UTC, ShuzZzle commented on CHANGELOG.md
> +* [ENHANCEMENT] Added api endpoints for Grafana 8 unified alerting
```suggestion
* [ENHANCEMENT] Added api endpoints for Grafana 8 unified alerting #291
```
missing pr number

2022-01-18 09:49 UTC, ShuzZzle requested changes
I just realised I never clicked that `Submit review` button. My bad

2022-01-30 13:37 UTC, ShuzZzle approved these changes

2022-01-30 13:38 UTC, ShuzZzle commented
Since this PR was kinda stale I decided to take-over. (was almost done anyway)

2022-02-01 18:49 UTC, kd7lxl approved these changes

2022-02-01 19:03 UTC, merged