Add guide for configuration am and ruler with mounted config maps
cortexproject/cortex-helm-chart pull request #313
Opened 2022-02-01 22:21 UTC by AkashSirimanna

**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2022-02-02 08:18 UTC, nschad commented
Hey @AkashSirimanna,

Thank's a lot for the great guide. However for the ruler you could also have used this https://github.com/cortexproject/cortex-helm-chart/blob/master/templates/ruler/ruler-dep.yaml#L136 which is a bit easier than manually mounting every tenant configmap.

Helm Values on how to use that for the **ruler** (doesn't exists for alertmanager) exist here: https://cortexproject.github.io/cortex-helm-chart/guides/configure_rules_via_configmap.html

2022-02-02 16:46 UTC, AkashSirimanna commented
Hi @nschad thank you for the review.

I can add a section for this as well. Maybe the user can choose between the 2, depending on what works for them.

The reason I decided to go with the mounting approach was this: We would need to define the rules under the `ruler.directories.tenant` key. In order to do this, we would need to have the rules defined either in the helm-chart or in a separate file which is in the same repository as the helm chart. In our case, our rules were defined elsewhere in a different repo, this is I we chose to go with the mounting approach.

If you wanted to use the directory approach, we would need to have the rules files in the same repo as the helm chart, which is usually not the case. In the mounting approach, you are able to have them maintained elsewhere.

Nonetheless, I see the benefits of both sides, possibly I could add another section to the guide with how to setup the directories method?

2022-02-02 17:23 UTC, nschad commented
> ruler.directories.tenant

I actually would like to 

> Hi @nschad thank you for the review.
> 
> I can add a section for this as well. Maybe the user can choose between the 2, depending on what works for them.
> 
> The reason I decided to go with the mounting approach was this: We would need to define the rules under the `ruler.directories.tenant` key. In order to do this, we would need to have the rules defined either in the helm-chart or in a separate file which is in the same repository as the helm chart. In our case, our rules were defined elsewhere in a different repo, this is I we chose to go with the mounting approach.
> 
> If you wanted to use the directory approach, we would need to have the rules files in the same repo as the helm chart, which is usually not the case. In the mounting approach, you are able to have them maintained elsewhere.
> 
> Nonetheless, I see the benefits of both sides, possibly I could add another section to the guide with how to setup the directories method?

I actually would like to deprecate `ruler.directories.tenant` because the alertmanager doesn't have it and I don't think its necessary thing to have

2022-02-02 17:31 UTC, AkashSirimanna commented
I see. If thats the case, what do you think of this guide then? If theres anything to add/remove/modify let me know.

2022-02-02 18:04 UTC, nschad reviewed
Great Guide. I just had some few points

2022-02-02 18:04 UTC, nschad commented on docs/guides/configure_ruler_and_alertmanager_with_configmap.markdown
> +      mountPath: /tmp
Same as above. We should really add that to the chart as the default. I keep forgetting it :(

2022-02-02 18:04 UTC, nschad commented on docs/guides/configure_ruler_and_alertmanager_with_configmap.markdown
> +Note that when we mount `tenantA-ruler-config`, we mount it under a folder which should be named after the tenant it corresponds to. In this situation, since we want `tenantA-ruler-config` to be the
```suggestion
Note that when we mount `tenantA-ruler-config`, we mount it under a folder which should be named after the tenant it corresponds to. In this situation, since we want `tenantA-ruler-config` to be the alerting rules for `tenantA`, we mount it under `/rules/tenantA`.
```

2022-02-02 18:15 UTC, AkashSirimanna commented on docs/guides/configure_ruler_and_alertmanager_with_configmap.markdown
> +    alertmanager_url: "http://_http-metrics._tcp.cortex-alertmanager/api/prom/alertmanager/"
Nope, removed 🙏

2022-02-02 18:19 UTC, AkashSirimanna commented
@nschad Thank you for the suggestions, I incorporated them and also changed `tenantA` to `tenantfoo`, i realized that capital letters in config map names are invalid.

I'll squash the commits once the changes look good

2022-02-02 18:33 UTC, AkashSirimanna commented
Good to go 😄

2022-02-02 18:53 UTC, nschad commented on docs/guides/configure_ruler_and_alertmanager_with_configmap.markdown
> +      emptyDir: {}
@AkashSirimanna What about this?

2022-02-02 19:22 UTC, AkashSirimanna commented on docs/guides/configure_ruler_and_alertmanager_with_configmap.markdown
> +      emptyDir: {}
Oops, forgot about this, yea I think you're right. I'm pretty sure it just needs a intermediate folder that is read-write

2022-02-02 19:26 UTC, nschad reviewed
Looks good however I won't get to testing it today but probably tomorrow :)

2022-02-02 19:51 UTC, AkashSirimanna commented
> Looks good however I won't get to testing it today but probably tomorrow :)

Sounds good! Im going to test it out in a bit to make sure everything is good

2022-02-02 20:35 UTC, AkashSirimanna commented
Tested on a local minikube cluster and it seems to be working :) I'll check back once you've got a chance to test it :)

2022-02-03 12:33 UTC, nschad requested changes
Guide verified! LGTM! However found a tiny typo

2022-02-03 12:33 UTC, nschad commented on docs/guides/configure_ruler_and_alertmanager_with_configmap.markdown
> +      name: tenantfoo-alertmanager-config
```suggestion
      name: alertmanager-config
```

needs to match what is in extraVolumeMounts

2022-02-03 16:05 UTC, nschad approved these changes
@AkashSirimanna Cool. I fixxed the Git mess I caused. Sorry about that. You probably wanna do
```
git fetch origin am-ruler-configmap-guide
git reset --hard origin/am-ruler-configmap-guide
```

but you are done so probably no need :)

2022-02-03 16:08 UTC, AkashSirimanna commented
> @AkashSirimanna Cool. I fixxed the Git mess I caused. Sorry about that. You probably wanna do
> 
> ```
> git fetch origin am-ruler-configmap-guide
> git reset --hard origin/am-ruler-configmap-guide
> ```
> 
> but you are done so probably no need :)

Ah no worries, I probably helped mess it up 🤣 .
Thanks for the review, hopefully this helps the community out a bit.

2022-02-03 16:31 UTC, nschad approved these changes

2022-02-03 17:00 UTC, kd7lxl commented on docs/guides/configure_ruler_and_alertmanager_with_configmap.markdown
> +In order to get this working, we must do a couple things
```suggestion
In order to get this working, we must do a couple things.
```

2022-02-03 17:01 UTC, kd7lxl commented on docs/guides/configure_ruler_and_alertmanager_with_configmap.markdown
> +**IMPORTANT** things to note
```suggestion
**IMPORTANT** things to note:
```

2022-02-03 17:03 UTC, kd7lxl commented on docs/guides/configure_ruler_and_alertmanager_with_configmap.markdown
> +- The section under `tenantfoo.yaml` is validated and interpreted exactly as a Prometheus rules configuration would be. How you configure this is completely up to you.
Let's include a reference to the documentation here.
```suggestion
- The section under `tenantfoo.yaml` is validated and interpreted exactly as a [Prometheus rules configuration](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/) would be. How you configure this is completely up to you.
```

2022-02-03 17:04 UTC, nschad commented
@AkashSirimanna Okay LOL.

I keep finding Issues but I think I got them all now (some of them have nothing to-do with you).

2022-02-03 17:05 UTC, nschad approved these changes

2022-02-03 17:13 UTC, kd7lxl commented on docs/guides/configure_ruler_and_alertmanager_with_configmap.markdown
> +**IMPORTANT** things to note
```suggestion
**IMPORTANT** things to note:
```

2022-02-03 17:13 UTC, kd7lxl commented on docs/guides/configure_ruler_and_alertmanager_with_configmap.markdown
> +- The section under `tenantfoo.yaml` is validated and interpreted exactly as a Prometheus alerting rules configuration would be. How you configure this is completely up to you.
```suggestion
- The section under `tenantfoo.yaml` is validated and interpreted exactly as a [Prometheus alerting rules configuration](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/) would be. How you configure this is completely up to you.
```

2022-02-03 17:16 UTC, nschad commented on docs/assets/scripts/copyCode.js
> +  const codeBlocks = document.querySelectorAll('div.highlighter-rouge');
about time, tehe

2022-02-03 17:20 UTC, AkashSirimanna commented
Thank you @kd7lxl, ill go ahead and make the changes

2022-02-03 18:06 UTC, kd7lxl approved these changes

2022-02-03 18:07 UTC, merged