Make alertmanager config optional in nginx.conf
cortexproject/cortex-helm-chart pull request #326
Opened 2022-03-01 14:39 UTC by WilliamCassanova

**What this PR does**:
Optionally allows for alertmanager section of nginx.conf to not be included based upon the `alertermanager.enabled` flag.

**Which issue(s) this PR fixes**:
Fixes #325

2022-03-01 14:44 UTC, nschad requested changes
Can you please also do this for the every distributor/alertmanager/ruler/.... endpoint? Otherwise this doesn't really make any sense

2022-03-01 14:44 UTC, nschad commented on CHANGELOG.md
> +* [ENHANCEMENT] Make altermanager config optional in nginx config #325
Don't declare a version yourself please. Just write your entry under master / unreleased

2022-03-01 14:44 UTC, nschad commented on CHANGELOG.md
> +### This Release includes BREAKING CHANGES
what happened here?

2022-03-01 15:07 UTC, WilliamCassanova commented on CHANGELOG.md
> +* [ENHANCEMENT] Make altermanager config optional in nginx config #325
Done.

2022-03-01 16:58 UTC, nschad requested changes

2022-03-01 16:58 UTC, nschad commented on templates/nginx/nginx-config.yaml
>          }
Can we warp this as well even though it's deprecated. should be `configs.enabled`

2022-03-01 17:08 UTC, WilliamCassanova commented on templates/nginx/nginx-config.yaml
>          }
Done.

2022-03-01 17:11 UTC, nschad commented on CHANGELOG.md
> +* [ENHANCEMENT] Make altermanager,distributor,rules and config.config configurations optional in nginx config #325
I would rephrase it to "Exclude cortex components endpoint when disabled from nginx config"

2022-03-01 17:13 UTC, nschad commented on CHANGELOG.md
> +* [ENHANCEMENT] Make altermanager,distributor,rules and config.config configurations optional in nginx config #325
Sorry @WilliamCassanova I mistyped. Should be 
> Exclude cortex components endpoint from nginx config when disabled

2022-03-01 17:34 UTC, nschad approved these changes

2022-03-01 18:16 UTC, WilliamCassanova commented
So once this is approved do one of the folks in https://github.com/cortexproject/cortex-helm-chart/blob/master/MAINTAINERS.md have to merge it?  I would assume the answer it yes.

2022-03-01 18:27 UTC, nschad commented
> So once this is approved do one of the folks in https://github.com/cortexproject/cortex-helm-chart/blob/master/MAINTAINERS.md have to merge it?  I would assume the answer it yes.

Waiting for 2nd approval and then we merge. Relax 😎

2022-03-01 18:32 UTC, kd7lxl approved these changes

2022-03-01 20:22 UTC, merged

2022-03-02 15:14 UTC, WilliamCassanova commented
So when I create a Fork and it eventually gets merged back to `Master` as was done yesterday. what if anything causes the `Chart.yaml` version to update and what actually generated a new release and tag.

I think I read in one of the CONTRIBUTING.md docs that I should not update the version.

The reason I asked is I just attempted to test this today and I am noticing the same failure as before:
```
host not found in upstream "cortex-alertmanager.cortex.svc.cluster.local" in /etc/nginx/nginx.conf:72
nginx: [emerg] host not found in upstream "cortex-alertmanager.cortex.svc.cluster.local" in /etc/nginx/nginx.conf:72
```

2022-03-02 15:18 UTC, nschad commented
> So when I create a Fork and it eventually gets merged back to `Master` as was done yesterday. what if anything causes the `Chart.yaml` version to update and what actually generates a new release and tag.
> 
> I think I read in one of the CONTRIBUTING.md docs that I should not update the version.
> 
> The reason I asked is I just attempted to test this today and I am noticing the same failure as before:
> 
> ```
> host not found in upstream "cortex-alertmanager.cortex.svc.cluster.local" in /etc/nginx/nginx.conf:72
> nginx: [emerg] host not found in upstream "cortex-alertmanager.cortex.svc.cluster.local" in /etc/nginx/nginx.conf:72
> ```

You need to wait for the release of a new version and deploy this helm chart from the master branch

2022-03-02 15:27 UTC, WilliamCassanova commented
Thanks...I just wanted to make sure I hadn't missed something.  I can locally in the meantime so no problems.