Add podManagementPolicy to store gateway statefulset template
cortexproject/cortex-helm-chart pull request #332
Opened 2022-03-10 00:18 UTC by mehta-ankit

Signed-off-by: Ankit Mehta <ankit.mehta@appian.com>

**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2022-03-10 08:11 UTC, nschad requested changes
thank you, a couple of things...

2022-03-10 08:11 UTC, nschad commented on templates/store-gateway/store-gateway-statefulset.yaml
> +  podManagementPolicy: "{{ .Values.store_gateway.statefulSet.podManagementPolicy }}"
```suggestion
  podManagementPolicy: {{ .Values.store_gateway.statefulSet.podManagementPolicy }}
```

drop the quotes please

2022-03-10 08:11 UTC, nschad commented on values.yaml
> +    podManagementPolicy: OrderedReady
Can we move this under `store_gateway.replicas` ?

2022-03-10 08:11 UTC, nschad commented on values.yaml
> +    # https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-management-policies
```suggestion
    # -- https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-management-policies
```

check helm-docs for the specific format https://github.com/norwoodj/helm-docs

2022-03-10 08:11 UTC, nschad commented on CHANGELOG.md
> +* [ENHANCEMENT] Allow StoreGateway podManagementPolicy to be changed
```suggestion
* [ENHANCEMENT] Allow StoreGateway podManagementPolicy to be changed #332
```

2022-03-10 08:11 UTC, nschad commented on values.yaml
> +    podManagementPolicy: OrderedReady
looks a bit weird there where it is (just formatting)

2022-03-10 08:14 UTC, nschad commented on values.yaml
> +    podManagementPolicy: OrderedReady
```yaml
store_gateway:
  enabled: true
  replicas: 1
  podManagementPolicy: OrderedReady
````

We don't have a deployment for the gateway therefore you can drop the `statefulSet` key

2022-03-10 13:53 UTC, mehta-ankit commented on values.yaml
> +    podManagementPolicy: OrderedReady
I wasn't sure so kept it like this for consistency sake, but i can change it.

2022-03-10 14:17 UTC, nschad commented on templates/store-gateway/store-gateway-statefulset.yaml
> +  podManagementPolicy: "{{ .Values.store_gateway.statefulSet.podManagementPolicy }}"
meh I guess we are not really consistent. I would prefer if you do wanna force quotes to use the helm `| quote` function. I'm good with either change. We might need to tackle this another day

2022-03-10 14:19 UTC, nschad commented on values.yaml
> +    podManagementPolicy: OrderedReady
Yep definitely remove the `statefulSet` subkey. Might not be consistent with the ingester but it'll get rid of any possible confusion

2022-03-10 19:27 UTC, mehta-ankit commented on templates/store-gateway/store-gateway-statefulset.yaml
> +  podManagementPolicy: "{{ .Values.store_gateway.statefulSet.podManagementPolicy }}"
will use ` | quote` 👍🏽

2022-03-10 19:28 UTC, mehta-ankit commented on values.yaml
> +    podManagementPolicy: OrderedReady
done!

2022-03-10 19:29 UTC, mehta-ankit commented
@nschad thanks for the review. Made the changes as requested.

2022-03-10 20:59 UTC, nschad commented
Don't write the README.md yourself. Have helm-docs generate it for you automatically. I can do that tomorrow for you if you want.

2022-03-10 21:24 UTC, mehta-ankit commented
> Don't write the README.md yourself. Have helm-docs generate it for you automatically. I can do that tomorrow for you if you want.

Ohh my bad 🤦🏽‍♂️ I did not understand your earlier comment properly. Used helm-docs to generate it now. Hopefully it ll all be good 🤞🏽 😅

2022-03-11 08:29 UTC, nschad approved these changes

2022-03-11 16:38 UTC, kd7lxl commented on CHANGELOG.md
> +* [ENHANCEMENT] Allow StoreGateway podManagementPolicy to be changed #332
This will need to move up to the unreleased section now that 1.4.0 is released.

2022-03-11 17:02 UTC, mehta-ankit commented on CHANGELOG.md
> +* [ENHANCEMENT] Allow StoreGateway podManagementPolicy to be changed #332
Will fix it

2022-03-11 17:04 UTC, mehta-ankit commented on CHANGELOG.md
> +* [ENHANCEMENT] Allow StoreGateway podManagementPolicy to be changed #332
Done!

2022-03-11 17:05 UTC, mehta-ankit commented
@kd7lxl This should be ready to merge!

2022-03-11 23:28 UTC, merged