Use .Release.Name in frontend.memcached.address to match service
cortexproject/cortex-helm-chart pull request #337
Opened 2022-03-14 18:55 UTC by elliottmb

**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2022-03-14 23:56 UTC, nschad commented on templates/_helpers.tpl
> -- "-frontend.memcached.addresses=dns+{{ template "cortex.fullname" . }}-memcached-frontend.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:11211"
I can see why you did this but I actually think this is the correct way and the usage of .Release.Name is wrong. So I rather have the other memcache url's corrected.

**But** I'll verify that tomorrow.

2022-03-15 07:54 UTC, nschad commented on templates/_helpers.tpl
> -- "-frontend.memcached.addresses=dns+{{ template "cortex.fullname" . }}-memcached-frontend.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:11211"
Yep if you were to use for examle `fullNameOverride` it corrently wouldn't work with `.Release.Name`. We need to change everything to `{{ template "cortex.fullname" . }}` @elliottmb

2022-03-15 07:55 UTC, nschad requested changes
see comment above

2022-03-16 02:53 UTC, elliottmb commented
@nschad Totally open to that change. This PR was to fix a bug we ran into where the query-frontend doesn't properly start if you try to enable this due to the mismatch of what the service is and what this was setting, so was wanting to fix that without changing the world. 

Would you want me to edit this PR to make that larger change or could that potentially be a follow up PR with this one still merged as an intermediate bug fix?

2022-03-16 07:56 UTC, nschad commented
> Would you be up to merging this PR as an intermediate bug fix given it's broken presently? I can follow up this PR to make that larger change at a later date.

I  don't feel comfortable doing this. What are your thoughts on this @kd7lxl ?

2022-03-16 15:48 UTC, nschad commented
> For context, this is the current behavior without the change.
> 
> ```
> level=warn ts=2022-03-16T15:41:16.49671671Z caller=resolver.go:133 msg="IP address lookup yielded no results. No host found or no addresses found" host=v1-cortex-memcached-frontend.cortex.svc.cluster.local
> level=error ts=2022-03-16T15:42:16.49494025Z caller=resolver.go:86 msg="failed to lookup IP addresses" host=v1-cortex-memcached-frontend.cortex.svc.cluster.local err="lookup v1-cortex-memcached-frontend.cortex.svc.cluster.local on 172.26.168.10:53: no such host"
> level=warn ts=2022-03-16T15:42:16.495017428Z caller=resolver.go:133 msg="IP address lookup yielded no results. No host found or no addresses found" host=v1-cortex-memcached-frontend.cortex.svc.cluster.local
> level=error ts=2022-03-16T15:43:16.502803721Z caller=resolver.go:86 msg="failed to lookup IP addresses" host=v1-cortex-memcached-frontend.cortex.svc.cluster.local err="lookup v1-cortex-memcached-frontend.cortex.svc.cluster.local on 172.26.168.10:53: no such host"
> ```
> 
> because
> 
> ```
> $ kubectl -n cortex get service
> NAME                                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
> v1-cortex-compactor                    ClusterIP   172.26.169.219   <none>        8080/TCP            8d
> ...
> v1-cortex-store-gateway-headless       ClusterIP   None             <none>        9095/TCP            8d
> v1-memcached-blocks                    ClusterIP   None             <none>        11211/TCP           8d
> v1-memcached-blocks-index              ClusterIP   None             <none>        11211/TCP           8d
> v1-memcached-blocks-index-metrics      ClusterIP   172.26.169.144   <none>        9150/TCP            8d
> v1-memcached-blocks-metadata           ClusterIP   None             <none>        11211/TCP           8d
> v1-memcached-blocks-metadata-metrics   ClusterIP   172.26.171.126   <none>        9150/TCP            8d
> v1-memcached-blocks-metrics            ClusterIP   172.26.170.195   <none>        9150/TCP            8d
> v1-memcached-frontend                  ClusterIP   None             <none>        11211/TCP           45h
> v1-memcached-frontend-metrics          ClusterIP   172.26.171.108   <none>        9150/TCP            45h
> ```

Can you tell me the name of your helm-release?

2022-03-16 15:50 UTC, elliottmb commented
I believe it's simply `v1`.

2022-03-16 16:07 UTC, nschad commented
@elliottmb Okay I think this pr would fix the problem. My thoughts appear to be wrong

2022-03-16 16:13 UTC, nschad approved these changes
thank you. Sorry for the confusion

2022-03-16 20:54 UTC, kd7lxl approved these changes

2022-03-16 20:55 UTC, merged