Add Overrides-Exporter
cortexproject/cortex-helm-chart pull request #360
Opened 2022-05-27 01:18 UTC by TaylorMutch

Signed-off-by: Taylor Mutch <taylormutch@gmail.com>

**What this PR does**:
Adds opt-in support for deploying the Cortex overrides exporter

**Which issue(s) this PR fixes**:
Fixes #359 

**Checklist**
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2022-05-27 08:22 UTC, nschad requested changes
awesome! thanks

2022-05-27 08:22 UTC, nschad commented on Chart.yaml
> +version: 1.5.2
Please don't bump the version yourself. We still have a manual process

2022-05-27 08:22 UTC, nschad commented on values.yaml
> +  # https://cortexmetrics.io/docs/guides/overrides-exporter/
```suggestion
  # -- https://cortexmetrics.io/docs/guides/overrides-exporter/
```

2022-05-27 08:22 UTC, nschad commented on values.yaml
> +    subPath:
```suggestion

```

unused can be removed

2022-05-28 22:07 UTC, TaylorMutch commented on Chart.yaml
> +version: 1.5.2
Roger that, will remove

2022-05-30 07:20 UTC, nschad requested changes

2022-05-30 07:20 UTC, nschad commented on CHANGELOG.md
> +# [FEATURE] Add Overrides-Exporter #360
```suggestion
* [FEATURE] Add Overrides-Exporter #360
```

2022-05-31 07:05 UTC, nschad approved these changes

2022-06-01 07:04 UTC, merged