Fix indentation for .Values.nginx.extraContainers
cortexproject/cortex-helm-chart pull request #374
Opened 2022-06-22 18:31 UTC by leonsp-ai

**What this PR does**: Fixes extraContainers indentation in nginx-dep

**Which issue(s) this PR fixes**:
Fixes #373

**Checklist**
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2022-06-23 17:50 UTC, kd7lxl commented on templates/nginx/nginx-dep.yaml
> +        {{ toYaml .Values.nginx.extraContainers | nindent 8}}
`nindent` will add a line break, so you'll want to trim it with `-`
```suggestion
        {{- toYaml .Values.nginx.extraContainers | nindent 8}}
```

2022-06-24 12:23 UTC, nschad requested changes
yup see comment from @kd7lxl and thank you @leonsp-ai for the fix :)

2022-06-24 14:12 UTC, leonsp-ai commented
@kd7lxl Thanks for taking a look! I've updated the PR 😁

2022-06-24 15:41 UTC, kd7lxl approved these changes

2022-06-24 21:06 UTC, nschad approved these changes

2022-06-24 21:06 UTC, merged