add nginx access log toggle
cortexproject/cortex-helm-chart pull request #402
Opened 2022-10-05 12:42 UTC by TuTuRyYE

**What this PR does**:
Add a toggle to enable/disable access logs in nginx (similar to loki helm chart)

**Which issue(s) this PR fixes**:
Nothing

**Checklist**
- [ ]

2022-10-05 12:58 UTC, nschad commented on templates/nginx/nginx-config.yaml
> +      {{- else }}
```suggestion
      {{- end }}
```

Should this be `end` ?

2022-10-06 09:16 UTC, nschad requested changes
Thank you. However you still need to update CHANGELOG.md with your PR! :)

Also you must sign your commits with DCO!

2022-10-06 12:13 UTC, TuTuRyYE commented
I'm not used to contributing, this is my first time. Thanks for your help :)

2022-10-06 13:23 UTC, nschad commented on templates/nginx/nginx-config.yaml
> +      {{- if .Values.nginx.config.verboseLogging }}
maybe we should rename this `accessLogging`. Verbose logging could be a number of things

2022-10-06 13:27 UTC, nschad commented
> I'm not used to contributing, this is my first time. Thanks for your help :)

Absolutely not a problem. Thank you for your contribution

2022-10-07 08:31 UTC, TuTuRyYE commented on README.md
> +| nginx.&ZeroWidthSpace;config.&ZeroWidthSpace;verboseLogging | bool | `true` | Enable access log to nginx |
I didn't know about this tool, thank you very much

2022-10-07 08:33 UTC, TuTuRyYE commented on templates/nginx/nginx-config.yaml
> +      {{- if .Values.nginx.config.verboseLogging }}
Actually after talking with my team, we would like only to ignore 2XX and 3XX status code request in the access logs.
I made the change in that direction, should I do some change on the PR description ? or should I create a new one ?

2022-10-10 07:15 UTC, nschad requested changes

2022-10-10 07:15 UTC, nschad commented on templates/nginx/nginx-config.yaml
> +      {{- if .Values.nginx.config.verboseLogging }}
Nope this PR is fine

2022-10-10 08:10 UTC, nschad commented on README.md
> -| nginx.&ZeroWidthSpace;config.&ZeroWidthSpace;basicAuthSecretName | string | `""` | (optional) Name of basic auth secret. In order to use this option, a secret with htpasswd formatted contents at th
This diff shouldn't be here. What helm-docs version are you using? The newest or v1.11.0?

I will also update that in our pipeline, our version is quite old

2022-10-10 08:11 UTC, nschad commented on README.md
> -| nginx.&ZeroWidthSpace;config.&ZeroWidthSpace;basicAuthSecretName | string | `""` | (optional) Name of basic auth secret. In order to use this option, a secret with htpasswd formatted contents at th
Probably is my old version though.

2022-10-10 08:21 UTC, nschad commented on README.md
> -| nginx.&ZeroWidthSpace;config.&ZeroWidthSpace;basicAuthSecretName | string | `""` | (optional) Name of basic auth secret. In order to use this option, a secret with htpasswd formatted contents at th
Yep this looks like our old version is at fault. Created a PR here: #404

2022-10-12 09:35 UTC, TuTuRyYE commented on templates/nginx/nginx-config.yaml
> +      {{- if .Values.gateway.verboseLogging }}
i copy/paste it from loki helm chart ...
I changed it sry

2022-10-14 13:31 UTC, nschad approved these changes

2022-10-14 15:00 UTC, kd7lxl approved these changes

2022-10-17 08:01 UTC, nschad commented
Hey @TuTuRyYE,

I shouldn't have pressed the GitHub "update-repo" button. What a mess. Anyway... DCO seems to be stuck.
Can you do the following on your PC in your cortex-helm-chart repo?

_UNLESS YOU HAVE LOCAL CHANGES IN THAT BRANCH_

```
git fetch origin add_logging_verbose_option_to_nginx
git reset --hard origin/add_logging_verbose_option_to_nginx
# e2de2f1f3dd1ecb95762851cf96c512027b71e8f should be last commit ID from master. Your branch is already rebased. This should clean up any potential weird authors.
git rebase -i e2de2f1f3dd1ecb95762851cf96c512027b71e8f -x "git commit --amend --reset-author -CHEAD"
# push it
git push -u origin add_logging_verbose_option_to_nginx -f
```

2022-10-17 08:21 UTC, merged