add purger components to cortex
cortexproject/cortex-helm-chart pull request #407
Opened 2022-10-21 02:10 UTC by AlexandreRoux

Signed-off-by: AlexandreRoux <alexandreroux42@protonmail.com>

**What this PR does**:
This PR add the purger service to cortex-helm 
https://cortexmetrics.io/docs/configuration/configuration-file/#purger_config
https://cortexmetrics.io/docs/api/#purger

The purger service is by default `disabled`.
The following services will have the extraArgs container edited with `-purger` :
+ querier
+ query-frontend
+ ruler
+ table-manager

**Which issue(s) this PR fixes**:
Fixes #145

**How to test**:
```
curl -v -XPOST --header "X-Scope-OrgID: fake" ${PURGER_URI}:${PURGER_FW_PORT}/purger/delete_tenant
curl -v -XGET --header "X-Scope-OrgID: fake" ${PURGER_URI}:${PURGER_FW_PORT}/purger/delete_tenant_status

# purger logs
level=info ts=2022-10-20T15:35:42.437155739Z caller=tenant_deletion_api.go:63 msg="tenant deletion mark in blocks storage created" user=fake

# compactor logs
level=info ts=2022-10-20T15:41:38.695346333Z caller=blocks_cleaner.go:144 component=cleaner msg="started blocks cleanup and maintenance"
level=info ts=2022-10-20T15:41:40.278579863Z caller=blocks_cleaner.go:197 component=cleaner org_id=fake msg="deleting blocks for tenant marked for deletion"
level=info ts=2022-10-20T15:41:42.781803963Z caller=blocks_cleaner.go:227 component=cleaner org_id=fake msg="deleted block" block=01G5R2V4HXHVZTBGQB9SPN7S86
level=info ts=2022-10-20T15:41:44.38291108Z caller=blocks_cleaner.go:227 component=cleaner org_id=fake msg="deleted block" block=01G5TNS0KB224V67447Z17KSE5
level=info ts=2022-10-20T15:41:46.022793531Z caller=blocks_cleaner.go:227 component=cleaner org_id=fake msg="deleted block" block=01G5X8J1QA7RFZ60A2KD0Q8Z4C
level=info ts=2022-10-20T15:42:08.123555156Z caller=blocks_cleaner.go:268 component=cleaner org_id=fake msg="updating finished time in tenant deletion mark"
...
...
level=info ts=2022-10-20T15:42:08.348427001Z caller=blocks_cleaner.go:148 component=cleaner msg="successfully completed blocks cleanup and maintenance"
```
**Checklist**
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2022-10-21 02:18 UTC, AlexandreRoux commented
This is my first ever PR and I tried my best to follow best practice but forgive my ignorance if I missed something.
 
I took example on other cortex services in order to create `templates/purger`.
I ran some tests to toggle block deletion as show in PR description, it works great so far but happy to run more tests if needed.

I look forward for guidance here.

2022-10-21 07:10 UTC, nschad commented
> This is my first ever PR and I tried my best to follow best practices but forgive my ignorance if I missed something.
> 
> I took example on other cortex services in order to create `templates/purger`. I ran some tests to toggle block deletion as show in PR description, it works great so far but happy to run more tests if needed.
> 
> I look forward for guidance here.

Looks really good. However you need to run https://github.com/norwoodj/helm-docs to update the table with the new values in the README.md. 

Simply run
```
helm-docs .
```
in your repo and push the new README.md

2022-10-21 08:48 UTC, nschad requested changes

2022-10-21 08:48 UTC, nschad commented on CHANGELOG.md
> +* [ENHANCEMENT] add purger components to cortex #407
```suggestion
* [FEATURE] add purger components to cortex #407
```
can you add this at the top please?

2022-10-21 09:21 UTC, nschad requested changes

2022-10-21 09:25 UTC, AlexandreRoux commented on CHANGELOG.md
> +* [FEATURE] add purger components to cortex #407
hehe sorry about that, changing now

2022-10-21 09:29 UTC, AlexandreRoux commented on CHANGELOG.md
> +* [FEATURE] add purger components to cortex #407
done via [6352f82](https://github.com/cortexproject/cortex-helm-chart/pull/407/commits/6352f8249d4d8d893a5ed6ab99977ec19ef065d6).

2022-10-21 09:33 UTC, nschad commented
@AlexandreRoux now you are missing a Sign-off-by on one or more commits :P.  You can do the following to fix that

* Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
* In your local branch, run: git rebase HEAD~4 --signoff
* Force push your changes to overwrite the branch: git push --force-with-lease origin add-purger

2022-10-21 09:49 UTC, AlexandreRoux commented
> @AlexandreRoux now you are missing a Sign-off-by on one or more commits :P. You can do the following to fix that
> 
>     * Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
> 
>     * In your local branch, run: git rebase HEAD~4 --signoff
> 
>     * Force push your changes to overwrite the branch: git push --force-with-lease origin add-purger

Very useful tips, seems it happen when I use the commit feature from github. 
I am taking notes down :D.

BTW I noticed a last things in my `git log` for commit 10686eb4ab45c614db8397e1cc7b9a3876b62227 where
```
Author: Alexandre Roux <alexandreroux42@protonmail.com>
```
differ from
```
Author: AlexandreRoux <alexandreroux42@protonmail.com>
```
Should I get that fixed too ?

2022-10-21 09:52 UTC, nschad commented
> > @AlexandreRoux now you are missing a Sign-off-by on one or more commits :P. You can do the following to fix that
> > ```
> > * Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
> > 
> > * In your local branch, run: git rebase HEAD~4 --signoff
> > 
> > * Force push your changes to overwrite the branch: git push --force-with-lease origin add-purger
> > ```
> 
> Very useful tips, seems it happen when I use the commit feature from github. I am taking notes down :D.



yep thats the issue. Happens all the time
> BTW I noticed a last things in my `git log` for commit [10686eb](https://github.com/cortexproject/cortex-helm-chart/commit/10686eb4ab45c614db8397e1cc7b9a3876b62227) where
> 
> ```
> Author: Alexandre Roux <alexandreroux42@protonmail.com>
> ```
> 
> differ from
> 
> ```
> Author: AlexandreRoux <alexandreroux42@protonmail.com>
> ```
> 
> Should I get that fixed too ?

Whatever you prefer. Doesn't really matter

2022-10-21 10:26 UTC, AlexandreRoux commented
> yep thats the issue. Happens all the time

> Whatever you prefer. Doesn't really matter

I had to do couple of tweak around with `rebase --exec` to get things sorted (included keeping gpg-sign) but it seems to be in good state now :D

2022-10-24 05:21 UTC, AlexandreRoux commented
@nschad - Is there anything needed from my side (test / changes / anything) ? Just trying to understand what are the next steps before merge.

2022-10-24 05:24 UTC, nschad approved these changes

2022-10-24 17:41 UTC, kd7lxl commented on values.yaml
> +  extraPorts: []
Looks like this was never actually implemented. Is it needed?

2022-10-24 17:41 UTC, kd7lxl commented on values.yaml
> +    prometheus.io/port: '8080'
Another concern I have -- and this is not entirely your fault because other deployments in this chart make the same mistake -- is that if `http_listen_port` is changed, this pod annotation will need to be changed to match.

https://github.com/cortexproject/cortex-helm-chart/blob/858b6e266951913c09659ef09c28932fa59fcb86/values.yaml#L73-L74

It would be easier for the user if this annotation was populated by the value. You could support references in values by using `tpl` near `toYaml`. Something like `{{- tpl (toYaml .) $ | nindent 8 }}`.

Not a blocker, since this is already inconsistent throughout the chart.

2022-10-25 11:34 UTC, nschad commented on values.yaml
> +  extraPorts: []
created an issue to track that issue

2022-10-25 11:38 UTC, merged

2022-10-26 06:30 UTC, AlexandreRoux commented
Thanks for the review, and glad I was able to contribute to the repo. I will try to do it more often in the future.