Start using autoscaling/v2 for HorizontalPodAutoscaler
cortexproject/cortex-helm-chart pull request #414
Opened 2022-12-05 15:56 UTC by GuyKomari

What this PR does / why we need it:

Problem: chart-testing is failing for:
"autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2"

Solution: update charts to start using autoscaler/v2

Signed-off-by: guykomari <guykomari@gmail.com>

2022-12-06 09:03 UTC, nschad reviewed
We should do something like this until 1.26+. To keep functionality with older clusters.

```yaml
{/*
Determine the policy api version
*/}}
{{- define "cortex.pdbVersion" -}}
{{- if or (.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget") (semverCompare ">=1.21" .Capabilities.KubeVersion.Version) -}}
policy/v1
{{- else -}}
policy/v1beta1
{{- end -}}
{{- end -}}
```

2022-12-06 13:48 UTC, nschad requested changes
Thank you, however please put the code in `templates/_helpers.tpl` global helpers file to avoid unnecessary code duplication just like with the pdbversion.

Then you can refer to it like this
```yaml
apiVersion: {{ include "cortex.hpaVersion" . }}
```

2022-12-06 15:14 UTC, nschad requested changes

2022-12-06 15:14 UTC, nschad commented on templates/_helpers.tpl
> +apiVersion: autoscaling/v2beta2
```suggestion
autoscaling/v2
{{- else -}}
autoscaling/v2beta2
```

2022-12-06 15:27 UTC, GuyKomari commented
> Thank you, however please put the code in `templates/_helpers.tpl` global helpers file to avoid unnecessary code duplication just like with the pdbversion.
> 
> Then you can refer to it like this
> 
> ```yaml
> apiVersion: {{ include "cortex.hpaVersion" . }}
> ```
> 
> _On a side note: We should also check if something changed between v1beta1 and v1 (but I guess it shouldn't have?)_

by the docs, it seems that nothing has changed.

2022-12-07 07:33 UTC, nschad requested changes

2022-12-07 07:33 UTC, nschad commented on templates/_helpers.tpl
> +{{- if or (.Capabilities.APIVersions.Has "autoscaling/v2") (semverCompare ">=1.23" .Capabilities.KubeVersion.Version) -}}
```suggestion
{{- if or (.Capabilities.APIVersions.Has "autoscaling/v2/HorizontalPodAutoscaler") (semverCompare ">=1.23" .Capabilities.KubeVersion.Version) -}}
```

Should be this

2022-12-07 08:11 UTC, nschad commented
@GuyKomari Check the Lint Test Job for error logs. There is some error evaluating the helm-chart.

Also please update the `CHANGELOG.md`

- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2022-12-07 09:06 UTC, GuyKomari commented
> @GuyKomari Check the Lint Test Job for error logs. There is some error evaluating the helm-chart.
> 
> Also please update the `CHANGELOG.md`
> 
> * [ ]  `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

I ran the ct lint locally and it passes now, so the github action should pass now.

2022-12-07 12:36 UTC, GuyKomari commented
@nschad once we merge this pr, when do we think we can also merge https://github.com/cortexproject/cortex-helm-chart/pull/413
and create a new release?

2022-12-07 13:31 UTC, nschad approved these changes

2022-12-07 19:26 UTC, kd7lxl approved these changes
LGTM, thank you!

2022-12-08 08:00 UTC, merged