cut release v2.2.1
cortexproject/cortex-helm-chart pull request #496
Opened 2024-04-12 10:54 UTC by locmai

**What this PR does**:

* [ENHANCEMENT] Alertmanager: Add `grpc` port #494 
* [ENHANCEMENT] Alertmanager: Expose 9094 TCP and UDP for gossip cluster #494
  * If the AlertManager headless service existed prior to applying the change, it will have only one port set, which is a known issue. See [kubernetes/kubernetes#39188](https://github.com/kubernetes/kubernetes/issues/39188). Re-creating the headless service can resolve this issue 

**Checklist**
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2024-04-12 12:14 UTC, nschad requested changes
Ty. But please cut version 2.3.0 as this includes changes not just fixing a problem

2024-04-12 12:14 UTC, nschad commented on CHANGELOG.md
> +## 2.2.1 / 2024-04-12
```suggestion
## 2.3.0 / 2024-04-12
```

2024-04-12 12:14 UTC, nschad commented on Chart.yaml
> +version: 2.2.1
```suggestion
version: 2.3.0
```

2024-04-12 16:22 UTC, kd7lxl approved these changes

2024-04-13 18:50 UTC, nschad approved these changes

2024-04-13 18:50 UTC, merged