Discoverable Alertmanager +UI+ other tweaks
cortexproject/cortex-helm-chart pull request #57
Opened 2020-10-05 20:32 UTC by ts-mini

Just attempting to contribute some of our changes to this chart upstream:

1) We're running multi-tenant - so we wanted to have ingress routes per scopeID when auth is enabled.  I've added this under distributor - but I'm not sure if this is the right place (as it ultimately creates a new route pointing to the nginx service)
2) I've added more configuration to the nginx service to make some of the debug/routes easier to hit from ingress.
3) Added a per-scope-id alertmanager path into nginx, configurable to alertmanager.ui.scopeids

I'm very flexible on implementation details - just interested in getting these style feature set upstream - so let me know if there are stylistic tweaks needed

2020-10-09 03:21 UTC, rsteneteg reviewed
Thanks for your contributions, had a few questions.

Really good start with the chart values in the readme

2020-10-09 03:21 UTC, rsteneteg commented on templates/nginx-config.yaml
> +{{- end }}
Since we are setting the orgID header based on the map, could we add a similar location rule that we have for the other endpoints to the alertmanager ui?

2020-10-09 03:21 UTC, rsteneteg commented on templates/ingress-distributor.yaml
> +    nginx.ingress.kubernetes.io/configuration-snippet: |
see my other comment about the map in the nginx config, based on that I don't think we need ingress resources for the distributors.
I would also try to avoid using nginx specific ingress annotations since users may use other ingress controllers.

2020-10-09 04:23 UTC, ts-mini commented
@rsteneteg I will work on your comments asap! thanks for the feedback

2020-10-09 14:06 UTC, khaines commented on templates/ingress-distributor.yaml
> +    nginx.ingress.kubernetes.io/configuration-snippet: |
I agree with both of Roger's items here. We need to keep ingress resource templates agnostic to the kind of controller used, plus in this case, we can use the Nginx config settings which negates the need for another ingress resource.

2020-10-09 15:28 UTC, khaines requested changes
Thank you @ts-mini for the work here. This PR has a number of changes in it, some of which I think are ready to merge now and others I don't think are a good fit. I'm going to try my best to classify them:

- Documentation: Huge thank you for creating the values documentation
- Alertmanger discovery: There's some feedback here, but this is a great addition
- Nginx tweaks/fixes: Updates for correcting ports, etc ... most welcome
- Multi-tenancy mapping: See my comment about this being a concern we've wanted to keep external from cortex. I really like your thoughts and approach to this, but I don't think it is a good fit for bringing into the chart.

2020-10-09 15:28 UTC, khaines commented on templates/nginx-config.yaml
> +{{- end }}
Something to be aware of: authenticating/mapping requests to OrgID's is a concern cortex has aimed to keep separate from any of the components. It is far too easy to leak in implementations specific details into this area, so the choice in the past is to keep them external.  

I really appreciate the thought that went into using a config driven way with the built-in nginx deployment to support a form of multi-tenancy. I just have to push back on it because it is a very implementation-specific approach to multitenancy.

2020-10-09 15:28 UTC, khaines commented on README.md
> +## Chart Values
Thank you so much for taking the time to document these! It's been a long pending item.

2020-10-09 16:17 UTC, ts-mini commented on templates/nginx-config.yaml
> +{{- end }}
Understood - I look forward to [this from "upstream" ](https://cortexmetrics.io/docs/roadmap/#auth-gateway).  I think what I will do is make a multi-tenant "add-on" chart then, that installs the nginx + distributor ingresses programmatically ( I think I can do this pretty easily and cleanly) and strip it out of this PR.

2020-10-09 17:54 UTC, ts-mini commented
I've made some changes - stripping out the stuff per @khaines comments.  I think this PR is a bit easier to digest now too - seeing as that complexity is gone.

I will work on making a secondary chart for our use that implements the multitenant separately from this chart - this will be a good path forward I think.  I understand the implications of disclosing implementation details - but may make this 'additional' chart available for anyone that wants to follow in my footsteps: deploy cortex, then deploy MT setup 'our/my way' - with the standard caveats of course.  If there's room in cortexproject for specific implementations - I wouldn't mind having it live here if y'all are ok with it, but that can be a future conversation.

2020-10-14 14:24 UTC, rsteneteg commented
LGTM

2020-10-18 02:17 UTC, khaines approved these changes
Thanks for making the adjustments @ts-mini ! This is a great addition.

LGTM also

2020-10-18 02:18 UTC, merged